spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.38.50.114:3306/aidev?serverTimezone=Asia/Seoul
    username: wisdom
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf3:
    decoupled-logic: true
#  servlet:
#    multipart:
#      max-file-size: 200MB
#      max-request-size: 100MB
#      location: /home/ec2-user/catchMind/photo/
  main:
    allow-bean-definition-overriding: true
server:
  port: 7070